window.SAYS_ASSESSMENT_RECORDS = [
    {
        category: 'required',
        subjectName: 'Mathematics',
        department: 'lower_primary',
        campus: 'Emmanuel Block',
        level: 'lower primary',
        teacher: 'Abigail Adu',
        term: '1st term',
        passMark: '70%',
        classScore: '50%',
        examScore: '50%'
    },
    {
        category: 'required',
        subjectName: 'Integrated Science',
        department: 'lower_primary',
        campus: 'Emmanuel Block',
        level: 'lower primary',
        teacher: 'Abigail Adu',
        term: '1st term',
        passMark: '80%',
        classScore: '50%',
        examScore: '50%'
    },
    {
        category: 'required',
        subjectName: 'History',
        department: 'lower_primary',
        campus: 'Susana',
        level: 'lower primary',
        teacher: 'Sir Gideon',
        term: '1st term',
        passMark: '80%',
        classScore: '50%',
        examScore: '50%'
    },
    {
        category: 'required',
        subjectName: 'English Language',
        department: 'lower_primary',
        campus: 'Susana',
        level: 'lower primary',
        teacher: 'Sir Gideon',
        term: '1st term',
        passMark: '80%',
        classScore: '50%',
        examScore: '50%'
    },
    {
        category: 'additional',
        subjectName: 'Religious and Moral Education',
        department: 'lower_primary',
        campus: 'Emmanuel Block',
        level: 'lower primary',
        teacher: 'Linda Mensah',
        term: '1st term',
        passMark: '75%',
        classScore: '50%',
        examScore: '50%'
    },
    {
        category: 'additional',
        subjectName: 'Creative Arts',
        department: 'lower_primary',
        campus: 'Susana',
        level: 'lower primary',
        teacher: 'Linda Mensah',
        term: '1st term',
        passMark: '75%',
        classScore: '50%',
        examScore: '50%'
    },
    {
        category: 'additional',
        subjectName: 'Ghanaian Language',
        department: 'lower_primary',
        campus: 'Emmanuel Block',
        level: 'lower primary',
        teacher: 'Sir Gideon',
        term: '1st term',
        passMark: '75%',
        classScore: '50%',
        examScore: '50%'
    },
    {
        category: 'required',
        subjectName: 'English Language',
        department: 'upper_primary',
        campus: 'Emmanuel Block',
        level: 'upper primary',
        teacher: 'Mavis Gyamfi',
        term: '1st term',
        passMark: '80%',
        classScore: '50%',
        examScore: '50%'
    },
    {
        category: 'required',
        subjectName: 'Mathematics',
        department: 'upper_primary',
        campus: 'Ezekiel Block',
        level: 'upper primary',
        teacher: 'Eunice Amoah',
        term: '1st term',
        passMark: '70%',
        classScore: '50%',
        examScore: '50%'
    },
    {
        category: 'required',
        subjectName: 'Integrated Science',
        department: 'upper_primary',
        campus: 'Ezekiel Block',
        level: 'upper primary',
        teacher: 'Eunice Amoah',
        term: '1st term',
        passMark: '80%',
        classScore: '50%',
        examScore: '50%'
    },
    {
        category: 'required',
        subjectName: 'Social Studies',
        department: 'upper_primary',
        campus: 'Ezekiel Block',
        level: 'upper primary',
        teacher: 'Micheal A. Asare',
        term: '1st term',
        passMark: '80%',
        classScore: '50%',
        examScore: '50%'
    },
    {
        category: 'additional',
        subjectName: 'Religious and Moral Education',
        department: 'upper_primary',
        campus: 'Ezekiel Block',
        level: 'upper primary',
        teacher: 'Linda Mensah',
        term: '1st term',
        passMark: '75%',
        classScore: '50%',
        examScore: '50%'
    },
    {
        category: 'additional',
        subjectName: 'ICT',
        department: 'upper_primary',
        campus: 'Ezekiel Block',
        level: 'upper primary',
        teacher: 'David Afful',
        term: '1st term',
        passMark: '75%',
        classScore: '50%',
        examScore: '50%'
    },
    {
        category: 'additional',
        subjectName: 'French',
        department: 'upper_primary',
        campus: 'Ezekiel Block',
        level: 'upper primary',
        teacher: 'Comfort Owusu',
        term: '1st term',
        passMark: '75%',
        classScore: '50%',
        examScore: '50%'
    },
    {
        category: 'required',
        subjectName: 'Mathematics',
        department: 'jhs',
        campus: 'Deacon Pokoo Block',
        level: 'JHS',
        teacher: 'Kwame Boateng',
        term: '1st term',
        passMark: '70%',
        classScore: '50%',
        examScore: '50%'
    },
    {
        category: 'required',
        subjectName: 'English Language',
        department: 'jhs',
        campus: 'Deacon Pokoo Block',
        level: 'JHS',
        teacher: 'Kwame Boateng',
        term: '1st term',
        passMark: '80%',
        classScore: '50%',
        examScore: '50%'
    },
    {
        category: 'required',
        subjectName: 'Integrated Science',
        department: 'jhs',
        campus: 'Deacon Pokoo Block',
        level: 'JHS',
        teacher: 'David Afful',
        term: '1st term',
        passMark: '80%',
        classScore: '50%',
        examScore: '50%'
    },
    {
        category: 'required',
        subjectName: 'Social Studies',
        department: 'jhs',
        campus: 'Deacon Pokoo Block',
        level: 'JHS',
        teacher: 'Micheal A. Asare',
        term: '1st term',
        passMark: '80%',
        classScore: '50%',
        examScore: '50%'
    },
    {
        category: 'additional',
        subjectName: 'ICT',
        department: 'jhs',
        campus: 'Deacon Pokoo Block',
        level: 'JHS',
        teacher: 'Comfort Owusu',
        term: '1st term',
        passMark: '75%',
        classScore: '50%',
        examScore: '50%'
    },
    {
        category: 'additional',
        subjectName: 'French',
        department: 'jhs',
        campus: 'Deacon Pokoo Block',
        level: 'JHS',
        teacher: 'Comfort Owusu',
        term: '1st term',
        passMark: '75%',
        classScore: '50%',
        examScore: '50%'
    },
    {
        category: 'additional',
        subjectName: 'Career Technology',
        department: 'jhs',
        campus: 'Deacon Pokoo Block',
        level: 'JHS',
        teacher: 'Kwame Boateng',
        term: '1st term',
        passMark: '75%',
        classScore: '50%',
        examScore: '50%'
    },
    {
        category: 'additional',
        subjectName: 'Religious and Moral Education',
        department: 'jhs',
        campus: 'Deacon Pokoo Block',
        level: 'JHS',
        teacher: 'David Afful',
        term: '1st term',
        passMark: '75%',
        classScore: '50%',
        examScore: '50%'
    }
];
